import type { CatalogPlant } from "@/types";

// Catálogo curado de especies aptas para jardinería urbana y sustentable.
// Los rangos de temperatura son promedios de máximas semanales tolerados.

export const PLANT_CATALOG: CatalogPlant[] = [
  {
    id: "lavanda",
    commonName: "Lavanda",
    scientificName: "Lavandula angustifolia",
    emoji: "💜",
    category: "aromática",
    matureWidthCm: 80,
    matureHeightCm: 70,
    light: "pleno sol",
    water: "bajo",
    tempMin: 8,
    tempMax: 32,
    summary:
      "Arbusto aromático mediterráneo, muy resistente a la sequía y atractivo para polinizadores.",
    advantages: [
      "Requiere muy poco riego una vez establecida",
      "Atrae abejas y mariposas al jardín",
      "Follaje perfumado durante todo el año",
      "Tolera suelos pobres y pedregosos",
    ],
    disadvantages: [
      "No soporta suelos encharcados ni riego excesivo",
      "Necesita poda anual para no volverse leñosa",
      "Rinde poco en zonas de humedad alta constante",
    ],
    planting: {
      soil: "Suelo suelto, arenoso y con muy buen drenaje (pH 6,5-7,5)",
      spacingCm: 60,
      depthCm: 25,
      season: "Otoño o principios de primavera",
      watering: "Riego profundo cada 10-15 días; suspender con lluvias",
      care: "Podá un tercio de la planta después de la floración",
    },
  },
  {
    id: "romero",
    commonName: "Romero",
    scientificName: "Salvia rosmarinus",
    emoji: "🌿",
    category: "aromática",
    matureWidthCm: 90,
    matureHeightCm: 120,
    light: "pleno sol",
    water: "bajo",
    tempMin: 8,
    tempMax: 36,
    summary:
      "Aromática perenne de uso culinario, ideal para bordes secos y macetas grandes.",
    advantages: [
      "Perenne y de crecimiento constante todo el año",
      "Uso culinario y medicinal inmediato",
      "Resiste sequía, viento y salinidad",
    ],
    disadvantages: [
      "Sensible a hongos si no hay circulación de aire",
      "Crecimiento lento en el primer año",
    ],
    planting: {
      soil: "Sustrato arenoso con drenaje rápido; evitar arcillas compactas",
      spacingCm: 70,
      depthCm: 30,
      season: "Primavera",
      watering: "Cada 10 días; dejar secar el sustrato entre riegos",
      care: "Pinzá las puntas para forzar ramificación compacta",
    },
  },
  {
    id: "helecho-serrucho",
    commonName: "Helecho serrucho",
    scientificName: "Nephrolepis exaltata",
    emoji: "🌱",
    category: "follaje",
    matureWidthCm: 70,
    matureHeightCm: 60,
    light: "sombra",
    water: "alto",
    tempMin: 14,
    tempMax: 30,
    summary:
      "Helecho de interior y patios sombreados, excelente para rincones húmedos sin sol directo.",
    advantages: [
      "Prospera en rincones sombríos donde poco más crece",
      "Mejora la humedad ambiente y filtra el aire",
      "Crecimiento rápido y denso",
    ],
    disadvantages: [
      "No tolera el sol directo ni el aire seco",
      "Requiere riego frecuente y constante",
      "Se daña con heladas",
    ],
    planting: {
      soil: "Sustrato rico en materia orgánica, húmedo pero drenado",
      spacingCm: 50,
      depthCm: 25,
      season: "Primavera-verano",
      watering: "2-3 veces por semana; pulverizar el follaje",
      care: "Retirá frondes secas y protegé del frío bajo 10 °C",
    },
  },
  {
    id: "agapanto",
    commonName: "Agapanto",
    scientificName: "Agapanthus africanus",
    emoji: "💙",
    category: "herbácea",
    matureWidthCm: 60,
    matureHeightCm: 90,
    light: "media sombra",
    water: "medio",
    tempMin: 10,
    tempMax: 33,
    summary:
      "Herbácea perenne de floración estival, muy usada en macizos y bordes de veredas.",
    advantages: [
      "Floración vistosa y prolongada en verano",
      "Muy bajo mantenimiento una vez establecido",
      "Se adapta a sol y media sombra",
    ],
    disadvantages: [
      "Puede volverse invasivo si no se divide la mata",
      "Follaje poco atractivo fuera de la floración",
    ],
    planting: {
      soil: "Suelo fértil con drenaje medio",
      spacingCm: 45,
      depthCm: 20,
      season: "Otoño o primavera",
      watering: "Semanal; aumentar durante la floración",
      care: "Dividí las matas cada 3-4 años",
    },
  },
  {
    id: "lantana",
    commonName: "Lantana",
    scientificName: "Lantana camara",
    emoji: "🌼",
    category: "arbusto",
    matureWidthCm: 120,
    matureHeightCm: 110,
    light: "pleno sol",
    water: "bajo",
    tempMin: 14,
    tempMax: 38,
    summary:
      "Arbusto florido de clima cálido, resistente al calor extremo y a la sequía.",
    advantages: [
      "Florece casi todo el año en climas cálidos",
      "Atrae mariposas y colibríes",
      "Soporta calor intenso y suelos degradados",
    ],
    disadvantages: [
      "Considerada invasora en varias regiones",
      "Follaje y frutos tóxicos si se ingieren",
      "Se hiela por debajo de 5 °C",
    ],
    planting: {
      soil: "Cualquier suelo con drenaje; tolera suelos pobres",
      spacingCm: 100,
      depthCm: 30,
      season: "Primavera",
      watering: "Cada 7-10 días; muy tolerante a la falta de agua",
      care: "Podá fuerte al final del invierno para renovar la planta",
    },
  },
  {
    id: "sedum",
    commonName: "Sedum / Uña de gato",
    scientificName: "Sedum spurium",
    emoji: "🪴",
    category: "cubresuelo",
    matureWidthCm: 35,
    matureHeightCm: 15,
    light: "pleno sol",
    water: "bajo",
    tempMin: 2,
    tempMax: 38,
    summary:
      "Suculenta cubresuelo ideal para espacios chicos, techos verdes y macetas expuestas.",
    advantages: [
      "Necesita muy poco sustrato y espacio",
      "Casi no requiere riego ni fertilización",
      "Excelente para techos verdes y jardineras",
    ],
    disadvantages: [
      "Se pudre con exceso de agua",
      "No tolera pisoteo frecuente",
    ],
    planting: {
      soil: "Mezcla arenosa para cactáceas, muy drenante",
      spacingCm: 25,
      depthCm: 12,
      season: "Primavera u otoño",
      watering: "Cada 15 días; menos en invierno",
      care: "Multiplicá por esquejes de tallo, enraízan solos",
    },
  },
  {
    id: "menta",
    commonName: "Menta",
    scientificName: "Mentha spicata",
    emoji: "🍃",
    category: "aromática",
    matureWidthCm: 40,
    matureHeightCm: 45,
    light: "media sombra",
    water: "alto",
    tempMin: 8,
    tempMax: 32,
    summary:
      "Aromática de crecimiento veloz, perfecta para macetas chicas y balcones con media sombra.",
    advantages: [
      "Crece muy rápido y se cosecha todo el año",
      "Ideal para espacios reducidos y macetas",
      "Repele algunas plagas de la huerta",
    ],
    disadvantages: [
      "Invasiva: sus rizomas colonizan el cantero",
      "Se marchita si le falta agua un par de días",
    ],
    planting: {
      soil: "Sustrato rico y siempre algo húmedo",
      spacingCm: 30,
      depthCm: 20,
      season: "Primavera",
      watering: "2-3 veces por semana",
      care: "Plantala en maceta separada para contener los rizomas",
    },
  },
  {
    id: "jazmin-del-pais",
    commonName: "Jazmín del país",
    scientificName: "Jasminum polyanthum",
    emoji: "🤍",
    category: "trepadora",
    matureWidthCm: 150,
    matureHeightCm: 300,
    light: "media sombra",
    water: "medio",
    tempMin: 10,
    tempMax: 34,
    summary:
      "Trepadora perfumada para muros y pérgolas en climas templados y subtropicales.",
    advantages: [
      "Perfume intenso en primavera",
      "Cubre muros y rejas rápidamente",
      "Aporta sombra verde en verano",
    ],
    disadvantages: [
      "Necesita estructura de soporte y poda regular",
      "Puede invadir espacios vecinos",
    ],
    planting: {
      soil: "Suelo fértil, drenado y con materia orgánica",
      spacingCm: 120,
      depthCm: 40,
      season: "Otoño o primavera",
      watering: "Semanal; más frecuente en verano",
      care: "Guiá los tallos y podá después de la floración",
    },
  },
  {
    id: "lirio-de-la-paz",
    commonName: "Lirio de la paz",
    scientificName: "Spathiphyllum wallisii",
    emoji: "🕊️",
    category: "follaje",
    matureWidthCm: 45,
    matureHeightCm: 55,
    light: "sombra",
    water: "medio",
    tempMin: 15,
    tempMax: 30,
    summary:
      "Planta de interior tolerante a poca luz, muy usada en patios cubiertos y oficinas.",
    advantages: [
      "Vive con luz indirecta escasa",
      "Purifica el aire de interiores",
      "Avisa la falta de riego decayendo sus hojas",
    ],
    disadvantages: [
      "Tóxica para mascotas si la mastican",
      "No tolera frío ni corrientes de aire",
    ],
    planting: {
      soil: "Sustrato universal con perlita para drenaje",
      spacingCm: 35,
      depthCm: 20,
      season: "Todo el año en interior",
      watering: "Semanal, manteniendo el sustrato apenas húmedo",
      care: "Limpiá las hojas con paño húmedo cada 15 días",
    },
  },
  {
    id: "cala",
    commonName: "Cala",
    scientificName: "Zantedeschia aethiopica",
    emoji: "🌸",
    category: "herbácea",
    matureWidthCm: 60,
    matureHeightCm: 80,
    light: "media sombra",
    water: "alto",
    tempMin: 8,
    tempMax: 30,
    summary:
      "Herbácea de zonas húmedas, excelente cerca de desagües, estanques o canteros sombreados.",
    advantages: [
      "Tolera suelos húmedos y anegados temporalmente",
      "Floración blanca elegante y prolongada",
      "Se naturaliza sin cuidados especiales",
    ],
    disadvantages: [
      "Savia irritante al contacto",
      "Entra en reposo y pierde follaje en verano seco",
    ],
    planting: {
      soil: "Suelo pesado y húmedo, rico en materia orgánica",
      spacingCm: 50,
      depthCm: 25,
      season: "Otoño",
      watering: "2 veces por semana; abundante en floración",
      care: "Cortá las flores marchitas al ras del suelo",
    },
  },
  {
    id: "cortadera",
    commonName: "Cortadera / Plumerillo",
    scientificName: "Cortaderia selloana",
    emoji: "🌾",
    category: "gramínea",
    matureWidthCm: 200,
    matureHeightCm: 250,
    light: "pleno sol",
    water: "bajo",
    tempMin: 5,
    tempMax: 36,
    summary:
      "Gramínea nativa de gran porte, resistente al viento y a la sequía, para espacios amplios.",
    advantages: [
      "Nativa, muy resistente al viento y a la sequía",
      "Refugio para aves e insectos benéficos",
      "Mínimo mantenimiento anual",
    ],
    disadvantages: [
      "Ocupa mucho espacio (2 m o más)",
      "Hojas cortantes: no apta cerca de juegos infantiles",
      "Alta inflamabilidad en seco",
    ],
    planting: {
      soil: "Cualquier suelo con drenaje razonable",
      spacingCm: 180,
      depthCm: 45,
      season: "Primavera",
      watering: "Cada 15 días el primer año; luego casi sin riego",
      care: "Podá la mata a 30 cm al final del invierno, con guantes",
    },
  },
  {
    id: "ciruelo-de-jardin",
    commonName: "Ciruelo de jardín",
    scientificName: "Prunus cerasifera",
    emoji: "🌳",
    category: "árbol",
    matureWidthCm: 400,
    matureHeightCm: 600,
    light: "pleno sol",
    water: "medio",
    tempMin: 4,
    tempMax: 32,
    summary:
      "Árbol chico de follaje rojizo, apto para veredas anchas y jardines de clima templado.",
    advantages: [
      "Sombra en verano y floración temprana en primavera",
      "Porte contenido comparado con otros árboles",
      "Tolera heladas moderadas",
    ],
    disadvantages: [
      "Necesita al menos 4 m de espacio libre",
      "Raíces superficiales que levantan solados",
      "Pierde las hojas en invierno",
    ],
    planting: {
      soil: "Suelo profundo, fértil y drenado",
      spacingCm: 400,
      depthCm: 60,
      season: "Invierno (a raíz desnuda) o principios de primavera",
      watering: "Semanal los dos primeros años",
      care: "Poda de formación en los primeros inviernos",
    },
  },
  {
    id: "cactus-columnar",
    commonName: "Cactus columnar",
    scientificName: "Trichocereus terscheckii",
    emoji: "🌵",
    category: "suculenta",
    matureWidthCm: 60,
    matureHeightCm: 200,
    light: "pleno sol",
    water: "bajo",
    tempMin: 10,
    tempMax: 42,
    summary:
      "Cactácea de zonas áridas, ideal para patios secos con sol intenso y riego casi nulo.",
    advantages: [
      "Sobrevive con lluvias mínimas",
      "Resiste temperaturas extremas y radiación alta",
      "Prácticamente sin mantenimiento",
    ],
    disadvantages: [
      "Espinas peligrosas en zonas de paso",
      "Crecimiento muy lento",
      "Se pudre con humedad de invierno",
    ],
    planting: {
      soil: "Mezcla mineral: arena gruesa, perlita y poca materia orgánica",
      spacingCm: 80,
      depthCm: 40,
      season: "Primavera-verano",
      watering: "Cada 20-30 días en verano; nada en invierno",
      care: "Evitá el riego cuando la temperatura baja de 12 °C",
    },
  },
  {
    id: "hosta",
    commonName: "Hosta",
    scientificName: "Hosta sieboldiana",
    emoji: "🍀",
    category: "follaje",
    matureWidthCm: 80,
    matureHeightCm: 50,
    light: "sombra",
    water: "medio",
    tempMin: 2,
    tempMax: 28,
    summary:
      "Perenne de hojas anchas para jardines fríos y sombríos, muy usada bajo árboles.",
    advantages: [
      "Excelente bajo árboles y en patios sombríos",
      "Muy resistente al frío y a las heladas",
      "Follaje decorativo de gran tamaño",
    ],
    disadvantages: [
      "Las babosas y caracoles la atacan con frecuencia",
      "Desaparece por completo en invierno",
      "No tolera sol directo del mediodía",
    ],
    planting: {
      soil: "Suelo húmedo, fresco y rico en humus",
      spacingCm: 60,
      depthCm: 25,
      season: "Otoño o principios de primavera",
      watering: "2 veces por semana en época de crecimiento",
      care: "Cubrí el suelo con mantillo para conservar humedad",
    },
  },
  {
    id: "tomillo",
    commonName: "Tomillo",
    scientificName: "Thymus vulgaris",
    emoji: "🌾",
    category: "cubresuelo",
    matureWidthCm: 30,
    matureHeightCm: 25,
    light: "pleno sol",
    water: "bajo",
    tempMin: 5,
    tempMax: 35,
    summary:
      "Cubresuelo aromático compacto, perfecto para macetas chicas y bordes soleados.",
    advantages: [
      "Ocupa muy poco espacio",
      "Aromática comestible de cosecha continua",
      "Resiste sequía y suelos pobres",
    ],
    disadvantages: [
      "Se ahoga en suelos húmedos o arcillosos",
      "Vida útil corta: conviene renovarlo cada 4 años",
    ],
    planting: {
      soil: "Sustrato arenoso, alcalino y muy drenante",
      spacingCm: 25,
      depthCm: 15,
      season: "Primavera",
      watering: "Cada 10-12 días",
      care: "Podá ligero después de la floración para mantener la forma",
    },
  },
  {
    id: "papiro",
    commonName: "Papiro enano",
    scientificName: "Cyperus alternifolius",
    emoji: "🎋",
    category: "herbácea",
    matureWidthCm: 60,
    matureHeightCm: 100,
    light: "media sombra",
    water: "alto",
    tempMin: 14,
    tempMax: 36,
    summary:
      "Planta palustre para climas cálidos y húmedos, tolera sustratos permanentemente mojados.",
    advantages: [
      "Ideal para zonas con lluvias abundantes o mal drenaje",
      "Crecimiento rápido y aspecto tropical",
      "Ayuda a filtrar agua en estanques",
    ],
    disadvantages: [
      "Requiere humedad constante, no tolera sequía",
      "Se hiela por debajo de 8 °C",
      "Puede expandirse fuera del cantero",
    ],
    planting: {
      soil: "Sustrato pesado, encharcado o al borde del agua",
      spacingCm: 50,
      depthCm: 30,
      season: "Primavera-verano",
      watering: "Mantener el sustrato siempre saturado",
      care: "Cortá los tallos secos a ras y dividí la mata cada 2 años",
    },
  },
];
