import type { CatalogPlant } from "@/types";

// Catálogo de especies para huerto urbano y doméstico.
// tempMin/tempMax = rango de temperatura media semanal tolerado (°C).
// Categorías: hortaliza-hoja | hortaliza-fruto | hortaliza-raíz |
//             legumbre | aromática | frutal | cucurbitácea

export const PLANT_CATALOG: CatalogPlant[] = [
  // ── HORTALIZAS DE HOJA ────────────────────────────────────────────────────
  {
    id: "lechuga-mantecosa",
    commonName: "Lechuga mantecosa",
    scientificName: "Lactuca sativa var. capitata",
    emoji: "🥬",
    category: "hortaliza-hoja",
    matureWidthCm: 30,
    matureHeightCm: 25,
    light: "media sombra",
    water: "alto",
    tempMin: 8,
    tempMax: 22,
    summary:
      "Hortaliza de ciclo corto (60-70 días), perfecta para macetas y canteros pequeños en climas frescos.",
    advantages: [
      "Ciclo muy corto: primera cosecha en 60 días",
      "Ideal para macetas y balcones",
      "Se puede resembrar cada 3 semanas para cosecha continua",
      "Combina bien con zanahorias y rabanitos",
    ],
    disadvantages: [
      "Se espiga (amarga) con calor superior a 25 °C",
      "Requiere riego regular para no marchiarse",
      "Sensible a caracoles y babosas",
    ],
    planting: {
      soil: "Sustrato suelto, fértil y con buen drenaje (pH 6-7)",
      spacingCm: 25,
      depthCm: 5,
      season: "Otoño, invierno y primavera (evitar verano caluroso)",
      watering: "Riego suave cada 2 días; mantener el suelo húmedo",
      care: "Cosechá las hojas externas primero para prolongar la producción",
    },
  },
  {
    id: "espinaca",
    commonName: "Espinaca",
    scientificName: "Spinacia oleracea",
    emoji: "🌿",
    category: "hortaliza-hoja",
    matureWidthCm: 30,
    matureHeightCm: 30,
    light: "media sombra",
    water: "alto",
    tempMin: 5,
    tempMax: 20,
    summary:
      "Hortaliza de estación fría, rica en hierro y vitaminas, lista en 40-50 días.",
    advantages: [
      "Tolera heladas leves (-5 °C puntual)",
      "Alto valor nutricional y sabor versátil",
      "Crece bien en espacios reducidos",
    ],
    disadvantages: [
      "Se espiga rápido con calor",
      "Requiere suelo rico en nitrógeno",
      "Sensible al exceso de sal en el suelo",
    ],
    planting: {
      soil: "Suelo fértil con abundante materia orgánica (pH 6,5-7)",
      spacingCm: 20,
      depthCm: 3,
      season: "Otoño e invierno",
      watering: "Diario en clima seco; cada 2 días en invierno",
      care: "Fertilizá con compost cada 3 semanas",
    },
  },
  {
    id: "acelga",
    commonName: "Acelga",
    scientificName: "Beta vulgaris subsp. cicla",
    emoji: "🥬",
    category: "hortaliza-hoja",
    matureWidthCm: 40,
    matureHeightCm: 50,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 30,
    summary:
      "Hortaliza resistente de ciclo largo, tolera calor y frío mejor que la espinaca.",
    advantages: [
      "Producción continua durante meses",
      "Tolera rangos amplios de temperatura",
      "Variedades de colores decorativas para el cantero",
    ],
    disadvantages: [
      "Ocupa bastante espacio para su rendimiento",
      "Sensible a la falta de boro en el suelo",
    ],
    planting: {
      soil: "Suelo profundo y fértil (pH 6,5-7,5)",
      spacingCm: 30,
      depthCm: 5,
      season: "Todo el año excepto verano muy caluroso",
      watering: "2-3 veces por semana",
      care: "Cortá las hojas externas para estimular rebrote",
    },
  },
  {
    id: "rucula",
    commonName: "Rúcula",
    scientificName: "Eruca vesicaria",
    emoji: "🌱",
    category: "hortaliza-hoja",
    matureWidthCm: 20,
    matureHeightCm: 25,
    light: "media sombra",
    water: "medio",
    tempMin: 8,
    tempMax: 24,
    summary:
      "Hoja picante de ciclo ultracorto (30-40 días), ideal para macetas pequeñas en interiores.",
    advantages: [
      "Lista en 30-40 días desde siembra",
      "Perfecta para macetas pequeñas y balcones",
      "Sabor distintivo muy valorado en cocina",
    ],
    disadvantages: [
      "Se espiga con calor y pierde sabor",
      "Ciclo corto: necesita resiembra frecuente",
    ],
    planting: {
      soil: "Cualquier sustrato fértil y bien drenado",
      spacingCm: 15,
      depthCm: 2,
      season: "Otoño, invierno y primavera",
      watering: "Cada 2 días; evitar encharcamiento",
      care: "Resembrá cada 3 semanas para tener producción continua",
    },
  },
  {
    id: "kale",
    commonName: "Kale / Col rizada",
    scientificName: "Brassica oleracea var. sabellica",
    emoji: "🥦",
    category: "hortaliza-hoja",
    matureWidthCm: 50,
    matureHeightCm: 60,
    light: "pleno sol",
    water: "medio",
    tempMin: 4,
    tempMax: 25,
    summary:
      "Superalimento resistente al frío, productivo durante meses con cosecha de hojas externas.",
    advantages: [
      "Muy resistente al frío y a las heladas",
      "Alta densidad nutricional",
      "Producción larga y continua",
    ],
    disadvantages: [
      "Susceptible a orugas de mariposa blanca",
      "Se pone amargo con calor extremo",
    ],
    planting: {
      soil: "Suelo rico en nitrógeno y bien drenado (pH 6,5-7)",
      spacingCm: 45,
      depthCm: 8,
      season: "Otoño e invierno; también primavera en zonas frías",
      watering: "2 veces por semana",
      care: "Cosechá las hojas inferiores para estimular la planta hacia arriba",
    },
  },
  // ── HORTALIZAS DE FRUTO ───────────────────────────────────────────────────
  {
    id: "tomate-cherry",
    commonName: "Tomate cherry",
    scientificName: "Solanum lycopersicum var. cerasiforme",
    emoji: "🍅",
    category: "hortaliza-fruto",
    matureWidthCm: 60,
    matureHeightCm: 150,
    light: "pleno sol",
    water: "medio",
    tempMin: 16,
    tempMax: 32,
    summary:
      "Variedad compacta ideal para macetas y balcones, muy productiva y de sabor intenso.",
    advantages: [
      "Altísima producción en poco espacio",
      "Frutos dulces y continuos durante meses",
      "Variedad determinada apta para maceta grande",
    ],
    disadvantages: [
      "Necesita tutorado (estaca o jaula)",
      "Susceptible a hongos con humedad alta",
      "Requiere polinización manual en interiores",
    ],
    planting: {
      soil: "Sustrato rico con compost, perlita y buen drenaje (pH 6-6,8)",
      spacingCm: 50,
      depthCm: 10,
      season: "Primavera (trasplante cuando superen los 15 °C nocturnos)",
      watering: "Regular y constante: cada 2 días; no mojar el follaje",
      care: "Despimpollar laterales, tutor y fertilizar con potasio en fructificación",
    },
  },
  {
    id: "pimiento",
    commonName: "Pimiento / Morrón",
    scientificName: "Capsicum annuum",
    emoji: "🫑",
    category: "hortaliza-fruto",
    matureWidthCm: 60,
    matureHeightCm: 70,
    light: "pleno sol",
    water: "medio",
    tempMin: 18,
    tempMax: 32,
    summary:
      "Frutal de huerto muy productivo, disponible en variedades dulces y picantes para maceta.",
    advantages: [
      "Versatilidad culinaria enorme",
      "Apto para maceta grande (20+ litros)",
      "Puede hibernar en climas suaves y rebrotar",
    ],
    disadvantages: [
      "Muy sensible al frío: muere con heladas",
      "Necesita al menos 6 horas de sol directo",
    ],
    planting: {
      soil: "Sustrato fértil con compost, bien drenado",
      spacingCm: 50,
      depthCm: 10,
      season: "Primavera tardía, cuando no haya riesgo de heladas",
      watering: "Cada 2 días; reducir al madurar los frutos",
      care: "Tutor ligero y fertilización con potasio cada 15 días",
    },
  },
  {
    id: "berenjena",
    commonName: "Berenjena",
    scientificName: "Solanum melongena",
    emoji: "🍆",
    category: "hortaliza-fruto",
    matureWidthCm: 70,
    matureHeightCm: 80,
    light: "pleno sol",
    water: "medio",
    tempMin: 20,
    tempMax: 35,
    summary:
      "Hortaliza de clima cálido con alta producción estival, tolera el calor mejor que el tomate.",
    advantages: [
      "Alta tolerancia al calor intenso de verano",
      "Larga temporada productiva",
      "Decorativa con flores violetas",
    ],
    disadvantages: [
      "Muy sensible al frío",
      "Requiere suelo muy fértil",
      "Susceptible al acaro de la araña roja",
    ],
    planting: {
      soil: "Sustrato muy fértil, cálido y drenado",
      spacingCm: 60,
      depthCm: 10,
      season: "Primavera tardía a verano",
      watering: "Abundante y regular; no tolera sequía",
      care: "Despimpollar exceso de flores para frutos de mayor tamaño",
    },
  },
  // ── HORTALIZAS DE RAÍZ ───────────────────────────────────────────────────
  {
    id: "zanahoria",
    commonName: "Zanahoria",
    scientificName: "Daucus carota subsp. sativus",
    emoji: "🥕",
    category: "hortaliza-raíz",
    matureWidthCm: 15,
    matureHeightCm: 30,
    light: "pleno sol",
    water: "medio",
    tempMin: 10,
    tempMax: 24,
    summary:
      "Hortaliza de raíz de ciclo medio (70-90 días), perfecta para canteros profundos y cajones.",
    advantages: [
      "Alta producción en poco espacio horizontal",
      "No necesita tutorado ni estructura",
      "Mejora la estructura del suelo con sus raíces",
    ],
    disadvantages: [
      "Necesita suelo suelto sin piedras (mínimo 30 cm profundidad)",
      "Sensible al exceso de nitrógeno (raíces bifurcadas)",
      "Germinación lenta (2-3 semanas)",
    ],
    planting: {
      soil: "Suelo suelto, arenoso y profundo sin rocas (pH 6-6,8)",
      spacingCm: 8,
      depthCm: 2,
      season: "Otoño y primavera",
      watering: "Regular y constante; evitar encharcamiento",
      care: "Aclareo a 8 cm cuando alcancen 5 cm de altura",
    },
  },
  {
    id: "rabanito",
    commonName: "Rabanito",
    scientificName: "Raphanus sativus",
    emoji: "🔴",
    category: "hortaliza-raíz",
    matureWidthCm: 10,
    matureHeightCm: 20,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 22,
    summary:
      "La hortaliza más rápida del huerto: lista en solo 25-30 días, ideal para niños y principiantes.",
    advantages: [
      "Cosecha en 25-30 días: record del huerto",
      "Excelente para ocupar espacios entre cultivos lentos",
      "Muy fácil y motivador para principiantes",
    ],
    disadvantages: [
      "Vida útil muy corta: se vuelve leñoso si no se cosecha a tiempo",
      "Se espiga con calor y días largos",
    ],
    planting: {
      soil: "Cualquier suelo suelto y bien drenado",
      spacingCm: 8,
      depthCm: 2,
      season: "Otoño, invierno y primavera",
      watering: "Regular; el suelo nunca debe secarse del todo",
      care: "Resembrá cada 2 semanas para producción escalonada",
    },
  },
  {
    id: "remolacha",
    commonName: "Remolacha / Betarraga",
    scientificName: "Beta vulgaris subsp. vulgaris",
    emoji: "🟣",
    category: "hortaliza-raíz",
    matureWidthCm: 20,
    matureHeightCm: 35,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 26,
    summary:
      "Hortaliza versátil: se consume tanto la raíz como las hojas, con ciclo de 60-80 días.",
    advantages: [
      "Aprovechás la raíz y las hojas jóvenes",
      "Muy resistente y fácil de cultivar",
      "Hermoso contraste de colores en el cantero",
    ],
    disadvantages: [
      "Semillas duras: conviene remojarlas 24h antes de sembrar",
      "Requiere aclareo para raíces grandes",
    ],
    planting: {
      soil: "Suelo fértil y bien trabajado, sin piedras",
      spacingCm: 15,
      depthCm: 3,
      season: "Primavera y otoño",
      watering: "2 veces por semana",
      care: "Aclareo a 15 cm cuando broten; usá los aclarados como verdura de hoja",
    },
  },
  // ── LEGUMBRES ─────────────────────────────────────────────────────────────
  {
    id: "poroto-chaucha",
    commonName: "Poroto / Chaucha verde",
    scientificName: "Phaseolus vulgaris",
    emoji: "🫘",
    category: "legumbre",
    matureWidthCm: 40,
    matureHeightCm: 50,
    light: "pleno sol",
    water: "medio",
    tempMin: 16,
    tempMax: 30,
    summary:
      "Legumbre de verano que fertiliza el suelo fijando nitrógeno; variedad enana para maceta.",
    advantages: [
      "Fija nitrógeno en el suelo: mejora el cantero",
      "Variedad enana no necesita tutorado",
      "Cosecha continua durante semanas",
    ],
    disadvantages: [
      "Muy sensible a las heladas",
      "Susceptible al mosaico del poroto (virus)",
      "No repetir en el mismo lugar más de 1 año seguido",
    ],
    planting: {
      soil: "Suelo suelto y bien drenado, poco fértil es suficiente",
      spacingCm: 15,
      depthCm: 4,
      season: "Primavera tardía y verano",
      watering: "Regular pero sin encharcar; critico en floración",
      care: "No fertilizar con nitrógeno: la planta lo produce sola",
    },
  },
  {
    id: "arvejas",
    commonName: "Arvejas / Guisantes",
    scientificName: "Pisum sativum",
    emoji: "🟢",
    category: "legumbre",
    matureWidthCm: 30,
    matureHeightCm: 80,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 20,
    summary:
      "Legumbre de estación fría muy productiva, se puede comer en vaina o desgranada.",
    advantages: [
      "Prospera en el frío cuando otras hortalizas no crecen",
      "Fija nitrógeno y mejora el suelo",
      "Alta productividad en espacio vertical",
    ],
    disadvantages: [
      "Necesita enrejado o tutorado para trepar",
      "Se termina con el calor del verano",
      "Susceptible al oídio en ambientes húmedos",
    ],
    planting: {
      soil: "Suelo suelto con buen drenaje, no muy fértil",
      spacingCm: 8,
      depthCm: 4,
      season: "Otoño tardío e invierno",
      watering: "Cada 3 días; crítico en floración",
      care: "Instalá una red o enrejado de 80-100 cm antes de sembrar",
    },
  },
  // ── AROMÁTICAS / HIERBAS CULINARIAS ──────────────────────────────────────
  {
    id: "albahaca",
    commonName: "Albahaca",
    scientificName: "Ocimum basilicum",
    emoji: "🌿",
    category: "aromática",
    matureWidthCm: 30,
    matureHeightCm: 40,
    light: "pleno sol",
    water: "medio",
    tempMin: 18,
    tempMax: 34,
    summary:
      "La reina de la cocina mediterránea, perfecta junto al tomate y en macetas de balcón.",
    advantages: [
      "Aroma y sabor incomparable recién cosechada",
      "Repele pulgones cuando se planta junto a tomates",
      "Ideal en macetas pequeñas en la cocina",
    ],
    disadvantages: [
      "Muere con el primer frío inferior a 12 °C",
      "Se espiga rápido: pinzar las flores continuamente",
      "Necesita mucho sol directo para buen sabor",
    ],
    planting: {
      soil: "Sustrato fértil y bien drenado",
      spacingCm: 25,
      depthCm: 3,
      season: "Primavera-verano (interior: todo el año con luz)",
      watering: "Cada 2 días; nunca encharcar",
      care: "Pinzá las flores para evitar el espigado y prolongar la planta",
    },
  },
  {
    id: "perejil",
    commonName: "Perejil",
    scientificName: "Petroselinum crispum",
    emoji: "🌾",
    category: "aromática",
    matureWidthCm: 25,
    matureHeightCm: 35,
    light: "media sombra",
    water: "medio",
    tempMin: 8,
    tempMax: 28,
    summary:
      "Hierba bianual imprescindible, tolera semisombra y macetas pequeñas durante todo el año.",
    advantages: [
      "Tolera semisombra: ideal para balcones con luz parcial",
      "Productivo durante meses seguidos",
      "Cosecha continua hoja por hoja",
    ],
    disadvantages: [
      "Germinación lenta (3 semanas): sembrar en almácigo",
      "Se espiga en el segundo año perdiendo sabor",
    ],
    planting: {
      soil: "Sustrato universal con algo de compost",
      spacingCm: 20,
      depthCm: 3,
      season: "Primavera y otoño",
      watering: "2-3 veces por semana",
      care: "Cortá desde la base para estimular el rebrote",
    },
  },
  {
    id: "cilantro",
    commonName: "Cilantro / Coriandro",
    scientificName: "Coriandrum sativum",
    emoji: "🌿",
    category: "aromática",
    matureWidthCm: 20,
    matureHeightCm: 40,
    light: "media sombra",
    water: "medio",
    tempMin: 10,
    tempMax: 25,
    summary:
      "Hierba de ciclo corto con hojas y semillas útiles en cocina; se espiga rápido con calor.",
    advantages: [
      "Hojas y semillas son aprovechables",
      "Atrae insectos benéficos al huerto",
      "Ciclo corto: resultado en pocas semanas",
    ],
    disadvantages: [
      "Se espiga muy rápido con calor",
      "Sabor intenso que no todos toleran",
      "Necesita resiembra frecuente",
    ],
    planting: {
      soil: "Sustrato ligero y bien drenado",
      spacingCm: 15,
      depthCm: 2,
      season: "Otoño y primavera",
      watering: "Riego moderado cada 2-3 días",
      care: "Resembrá cada 3 semanas en distintos recipientes",
    },
  },
  {
    id: "menta",
    commonName: "Menta",
    scientificName: "Mentha spicata",
    emoji: "🍃",
    category: "aromática",
    matureWidthCm: 40,
    matureHeightCm: 45,
    light: "media sombra",
    water: "alto",
    tempMin: 8,
    tempMax: 30,
    summary:
      "Aromática invasiva de crecimiento veloz, perfecta en maceta separada del resto del huerto.",
    advantages: [
      "Crece muy rápido y cosecha continua",
      "Repele plagas de la huerta",
      "Excelente en infusiones y cocina",
    ],
    disadvantages: [
      "Invasiva: sus rizomas colonizan todo si no se contiene",
      "Se marchita si le falta agua unos días",
    ],
    planting: {
      soil: "Sustrato rico y siempre húmedo",
      spacingCm: 30,
      depthCm: 5,
      season: "Primavera (por rizomas o esquejes)",
      watering: "2-3 veces por semana",
      care: "Siempre en maceta separada para contener los rizomas",
    },
  },
  {
    id: "ciboulette",
    commonName: "Ciboulette / Cebollín",
    scientificName: "Allium schoenoprasum",
    emoji: "🌱",
    category: "aromática",
    matureWidthCm: 20,
    matureHeightCm: 30,
    light: "pleno sol",
    water: "medio",
    tempMin: 6,
    tempMax: 28,
    summary:
      "Perenne compacta de la familia de las cebollas, ideal para macetas pequeñas y bordes de cantero.",
    advantages: [
      "Perenne: dura años sin resembrar",
      "Muy compacta para espacios pequeños",
      "Flores comestibles y decorativas",
    ],
    disadvantages: [
      "Producción limitada comparada con cebolla de bulbo",
      "Necesita dividirse cada 2-3 años",
    ],
    planting: {
      soil: "Cualquier sustrato fértil y drenado",
      spacingCm: 15,
      depthCm: 3,
      season: "Primavera u otoño",
      watering: "2 veces por semana",
      care: "Cortá a 5 cm del suelo para estimular rebrote vigoroso",
    },
  },
  {
    id: "tomillo",
    commonName: "Tomillo",
    scientificName: "Thymus vulgaris",
    emoji: "🌾",
    category: "aromática",
    matureWidthCm: 30,
    matureHeightCm: 25,
    light: "pleno sol",
    water: "bajo",
    tempMin: 5,
    tempMax: 35,
    summary:
      "Cubresuelo aromático mediterráneo, resistente a la sequía y excelente para bordes del huerto.",
    advantages: [
      "Resistente a sequía y suelos pobres",
      "Perenne con cosecha continua",
      "Repele plagas de la huerta",
    ],
    disadvantages: [
      "Se pudre en suelos húmedos o arcillosos",
      "Vida útil de 4 años: conviene renovarlo",
    ],
    planting: {
      soil: "Sustrato arenoso y muy drenante",
      spacingCm: 25,
      depthCm: 15,
      season: "Primavera",
      watering: "Cada 10-12 días",
      care: "Podá después de la floración para mantener la forma compacta",
    },
  },
  {
    id: "oregano",
    commonName: "Orégano",
    scientificName: "Origanum vulgare",
    emoji: "🌿",
    category: "aromática",
    matureWidthCm: 40,
    matureHeightCm: 50,
    light: "pleno sol",
    water: "bajo",
    tempMin: 8,
    tempMax: 36,
    summary:
      "Aromática perenne mediterránea imprescindible en la cocina, muy resistente y de bajo mantenimiento.",
    advantages: [
      "Perenne y muy poco exigente",
      "Sabor más intenso con estrés hídrico leve",
      "Atrae polinizadores al huerto",
    ],
    disadvantages: [
      "Pierde aroma en exceso de humedad",
      "Precisa renovación cada 4-5 años",
    ],
    planting: {
      soil: "Suelo suelto, pobre y bien drenado",
      spacingCm: 30,
      depthCm: 10,
      season: "Primavera",
      watering: "Cada 10 días; dejar secar entre riegos",
      care: "Cosechá antes de la floración para máximo aroma",
    },
  },
  // ── CUCURBITÁCEAS ─────────────────────────────────────────────────────────
  {
    id: "zapallito-redondo",
    commonName: "Zapallito redondo",
    scientificName: "Cucurbita maxima var. zapallito",
    emoji: "🥒",
    category: "cucurbitácea",
    matureWidthCm: 80,
    matureHeightCm: 50,
    light: "pleno sol",
    water: "alto",
    tempMin: 18,
    tempMax: 34,
    summary:
      "Cucurbitácea de verano muy productiva, perfecta para huertos latinoamericanos con espacio moderado.",
    advantages: [
      "Producción abundante y continua en verano",
      "Parte del ciclo culinario rioplatense",
      "Las flores también son comestibles",
    ],
    disadvantages: [
      "Necesita bastante espacio (80+ cm)",
      "Muy sensible al frío y a las heladas",
      "Susceptible a oídio en otoño",
    ],
    planting: {
      soil: "Suelo fértil con abundante compost",
      spacingCm: 80,
      depthCm: 3,
      season: "Primavera tardía",
      watering: "Abundante: cada 2 días; crítico en fructificación",
      care: "Polinizá manualmente si no hay insectos; cosechá chico para más producción",
    },
  },
  {
    id: "pepino",
    commonName: "Pepino",
    scientificName: "Cucumis sativus",
    emoji: "🥒",
    category: "cucurbitácea",
    matureWidthCm: 50,
    matureHeightCm: 150,
    light: "pleno sol",
    water: "alto",
    tempMin: 18,
    tempMax: 32,
    summary:
      "Trepadora productiva de verano que aprovecha el espacio vertical con tutor o enrejado.",
    advantages: [
      "Aprovecha espacio vertical con tutorado",
      "Cosecha en 50-60 días desde trasplante",
      "Altísima productividad en verano",
    ],
    disadvantages: [
      "Necesita enrejado o tutorado",
      "Muy sensible al frío y a la sequía",
      "Susceptible al mildiu polvoroso",
    ],
    planting: {
      soil: "Sustrato rico y cálido, con buen drenaje",
      spacingCm: 40,
      depthCm: 3,
      season: "Primavera tardía a verano",
      watering: "Diario en verano; nunca mojar las hojas",
      care: "Podá lateral para conducir la planta hacia arriba",
    },
  },
  // ── FRUTALES COMPACTOS ────────────────────────────────────────────────────
  {
    id: "frutilla",
    commonName: "Frutilla / Fresa",
    scientificName: "Fragaria × ananassa",
    emoji: "🍓",
    category: "frutal",
    matureWidthCm: 30,
    matureHeightCm: 20,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 26,
    summary:
      "Frutal compacto y de rápido retorno, ideal para cajones, macetas y jardines verticales.",
    advantages: [
      "Rápido: frutos en el primer año",
      "Perfecta para macetas, cajones y jardines verticales",
      "Se propaga sola mediante estolones",
    ],
    disadvantages: [
      "Atrae caracoles y pájaros",
      "Producción concentrada: 3-4 semanas al año",
      "Conviene renovar la planta cada 3 años",
    ],
    planting: {
      soil: "Sustrato ligeramente ácido (pH 5,5-6,5) y bien drenado",
      spacingCm: 25,
      depthCm: 8,
      season: "Otoño (plantines) o primavera temprana",
      watering: "Regular cada 2 días; nunca encharcar la corona",
      care: "Cubrí con paja bajo los frutos; eliminá estolones si querés más fruta",
    },
  },
  {
    id: "limón-patio",
    commonName: "Limón (variedad patio)",
    scientificName: "Citrus × limon 'Patio'",
    emoji: "🍋",
    category: "frutal",
    matureWidthCm: 80,
    matureHeightCm: 100,
    light: "pleno sol",
    water: "medio",
    tempMin: 10,
    tempMax: 36,
    summary:
      "Cítrico enano para maceta grande, productivo y perfumado durante todo el año en climas cálidos.",
    advantages: [
      "Produce frutos casi todo el año en clima suave",
      "Perfume intenso de flor y hoja",
      "Apto para maceta de 40+ cm",
    ],
    disadvantages: [
      "Sensible a heladas sostenidas",
      "Requiere fertilización específica para cítricos",
      "Susceptible a cochinilla y mosca de la fruta",
    ],
    planting: {
      soil: "Sustrato específico para cítricos, ácido (pH 5,5-6,5)",
      spacingCm: 80,
      depthCm: 20,
      season: "Primavera (trasplante a maceta final de 40 litros)",
      watering: "Profundo cada 4-5 días; reducir en invierno",
      care: "Fertilizá con abono para cítricos cada 30 días en primavera-verano",
    },
  },
  {
    id: "arándano",
    commonName: "Arándano",
    scientificName: "Vaccinium corymbosum",
    emoji: "🫐",
    category: "frutal",
    matureWidthCm: 80,
    matureHeightCm: 120,
    light: "pleno sol",
    water: "medio",
    tempMin: 2,
    tempMax: 28,
    summary:
      "Frutal ácido perenne en maceta grande, requiere suelo ácido y produce durante semanas en verano.",
    advantages: [
      "Resistente al frío: soporta heladas intensas",
      "Producción anual durante años",
      "Hojas otoñales decorativas",
    ],
    disadvantages: [
      "Requiere suelo muy ácido (pH 4,5-5,5): difícil de mantener",
      "Necesita 2 plantas para polinización cruzada",
      "Tardío: primer cosecha recién al 2do año",
    ],
    planting: {
      soil: "Sustrato muy ácido con turba y perlita (pH 4,5-5,5)",
      spacingCm: 80,
      depthCm: 20,
      season: "Otoño o invierno (a raíz desnuda)",
      watering: "Regular con agua sin cloro; cada 3 días en verano",
      care: "Acidificá el sustrato con sulfato de hierro; buen drenaje obligatorio",
    },
  },
  // ── CEBOLLA Y PARIENTES ───────────────────────────────────────────────────
  {
    id: "cebolla-de-verdeo",
    commonName: "Cebolla de verdeo",
    scientificName: "Allium fistulosum",
    emoji: "🧅",
    category: "hortaliza-hoja",
    matureWidthCm: 10,
    matureHeightCm: 40,
    light: "pleno sol",
    water: "medio",
    tempMin: 8,
    tempMax: 28,
    summary:
      "La más productiva del huerto urbano: ocupa mínimo espacio y se cosecha en 60 días.",
    advantages: [
      "Mínimo espacio: 10 cm entre plantas",
      "Cosecha continua cortando desde la base",
      "Se replanta fácilmente de esquejes",
    ],
    disadvantages: [
      "Sabor fuerte que no todos toleran en crudo",
      "Requiere resiembra periódica",
    ],
    planting: {
      soil: "Sustrato fértil con buen drenaje",
      spacingCm: 10,
      depthCm: 3,
      season: "Todo el año en climas templados",
      watering: "2-3 veces por semana",
      care: "Cosechá dejando 5 cm desde la base para que rebrote",
    },
  },
  {
    id: "ajo",
    commonName: "Ajo",
    scientificName: "Allium sativum",
    emoji: "🧄",
    category: "hortaliza-raíz",
    matureWidthCm: 15,
    matureHeightCm: 50,
    light: "pleno sol",
    water: "bajo",
    tempMin: 5,
    tempMax: 26,
    summary:
      "Bulbo aromático de ciclo largo (5-7 meses), excelente compañero de tomates y morrón.",
    advantages: [
      "Repele plagas de la huerta naturalmente",
      "Muy bajo mantenimiento durante el ciclo",
      "Un diente produce un bulbo completo",
    ],
    disadvantages: [
      "Ciclo largo: 5-7 meses",
      "Necesita período de frío para bulbificación",
      "Hoja verde poco atractiva",
    ],
    planting: {
      soil: "Suelo suelto, fértil y drenado (pH 6-7)",
      spacingCm: 15,
      depthCm: 5,
      season: "Otoño (plantación de dientes)",
      watering: "Cada 7-10 días; suspender cuando el follaje amarillee",
      care: "Cosechá cuando la mitad del follaje esté seco; curar al sol 2 semanas",
    },
  },
];
